/* GENERATED by tat-satellite-render s2_products_export.py -- do not
 * hand-edit. Regenerate after registry/recipe changes:
 *   python s2_products_export.py --out <TAT>/satellite/explorer
 * Presentation mirror of the registry suite (SSOT: s2_recipes +
 * s2_registry); products.json on R2 carries the same rows. */
window.TVProducts = {
  "base": "https://cdn.triple-a-tropics.com/shadow/",
  "sector": "conus",
  "products": [
    {
      "key": "ir",
      "id": "goes19-conus-ir",
      "path": "sat/goes19/conus/ir",
      "title": "C13 · 10.3 µm (Clean IR)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          {
            "t": "40",
            "p": 0.0
          },
          {
            "t": "0",
            "p": 0.2963
          },
          {
            "t": "−40",
            "p": 0.5926
          },
          {
            "t": "−80",
            "p": 0.8889
          }
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "sandwich",
      "id": "goes19-conus-sandwich",
      "path": "sat/goes19/conus/sandwich",
      "title": "Sandwich (VIS × IR)",
      "group": "composite",
      "bt": true,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          {
            "t": "40",
            "p": 0.0
          },
          {
            "t": "0",
            "p": 0.2963
          },
          {
            "t": "−40",
            "p": 0.5926
          },
          {
            "t": "−80",
            "p": 0.8889
          }
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "truecolor",
      "id": "goes19-conus-truecolor",
      "path": "sat/goes19/conus/truecolor",
      "title": "True Color (GeoColor-lite)",
      "group": "composite",
      "bt": false,
      "dayOnly": false,
      "cbar": null
    },
    {
      "key": "airmass",
      "id": "goes19-conus-airmass",
      "path": "sat/goes19/conus/airmass",
      "title": "Air Mass RGB",
      "group": "rgb",
      "bt": true,
      "dayOnly": false,
      "cbar": null
    },
    {
      "key": "ash",
      "id": "goes19-conus-ash",
      "path": "sat/goes19/conus/ash",
      "title": "Ash RGB",
      "group": "rgb",
      "bt": true,
      "dayOnly": false,
      "cbar": null
    },
    {
      "key": "daycloudphase",
      "id": "goes19-conus-daycloudphase",
      "path": "sat/goes19/conus/daycloudphase",
      "title": "Day Cloud Phase Distinction",
      "group": "rgb",
      "bt": true,
      "dayOnly": true,
      "cbar": null
    },
    {
      "key": "dayconvection",
      "id": "goes19-conus-dayconvection",
      "path": "sat/goes19/conus/dayconvection",
      "title": "Day Convection RGB",
      "group": "rgb",
      "bt": false,
      "dayOnly": true,
      "cbar": null
    },
    {
      "key": "daylandcloud",
      "id": "goes19-conus-daylandcloud",
      "path": "sat/goes19/conus/daylandcloud",
      "title": "Day Land Cloud (Natural Color)",
      "group": "rgb",
      "bt": false,
      "dayOnly": true,
      "cbar": null
    },
    {
      "key": "snowfog",
      "id": "goes19-conus-snowfog",
      "path": "sat/goes19/conus/snowfog",
      "title": "Day Snow-Fog RGB",
      "group": "rgb",
      "bt": false,
      "dayOnly": true,
      "cbar": null
    },
    {
      "key": "dust",
      "id": "goes19-conus-dust",
      "path": "sat/goes19/conus/dust",
      "title": "Dust RGB",
      "group": "rgb",
      "bt": true,
      "dayOnly": false,
      "cbar": null
    },
    {
      "key": "firetemp",
      "id": "goes19-conus-firetemp",
      "path": "sat/goes19/conus/firetemp",
      "title": "Fire Temperature RGB",
      "group": "rgb",
      "bt": false,
      "dayOnly": true,
      "cbar": null
    },
    {
      "key": "nightmicro",
      "id": "goes19-conus-nightmicro",
      "path": "sat/goes19/conus/nightmicro",
      "title": "Nighttime Microphysics",
      "group": "rgb",
      "bt": true,
      "dayOnly": false,
      "cbar": null
    },
    {
      "key": "c01",
      "id": "goes19-conus-c01",
      "path": "sat/goes19/conus/c01",
      "title": "C01 · 0.47 µm (Blue)",
      "group": "channel",
      "bt": false,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/gray_refl.png",
        "ticks": [
          {
            "t": "100",
            "p": 0.0
          },
          {
            "t": "50",
            "p": 0.5
          },
          {
            "t": "0",
            "p": 1.0
          }
        ],
        "cap": "Reflectance (%)"
      }
    },
    {
      "key": "c02",
      "id": "goes19-conus-c02",
      "path": "sat/goes19/conus/c02",
      "title": "C02 · 0.64 µm (Red visible)",
      "group": "channel",
      "bt": false,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/gray_refl.png",
        "ticks": [
          {
            "t": "100",
            "p": 0.0
          },
          {
            "t": "50",
            "p": 0.5
          },
          {
            "t": "0",
            "p": 1.0
          }
        ],
        "cap": "Reflectance (%)"
      }
    },
    {
      "key": "c03",
      "id": "goes19-conus-c03",
      "path": "sat/goes19/conus/c03",
      "title": "C03 · 0.86 µm (Veggie NIR)",
      "group": "channel",
      "bt": false,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/gray_refl.png",
        "ticks": [
          {
            "t": "100",
            "p": 0.0
          },
          {
            "t": "50",
            "p": 0.5
          },
          {
            "t": "0",
            "p": 1.0
          }
        ],
        "cap": "Reflectance (%)"
      }
    },
    {
      "key": "c04",
      "id": "goes19-conus-c04",
      "path": "sat/goes19/conus/c04",
      "title": "C04 · 1.37 µm (Cirrus)",
      "group": "channel",
      "bt": false,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/gray_refl.png",
        "ticks": [
          {
            "t": "100",
            "p": 0.0
          },
          {
            "t": "50",
            "p": 0.5
          },
          {
            "t": "0",
            "p": 1.0
          }
        ],
        "cap": "Reflectance (%)"
      }
    },
    {
      "key": "c05",
      "id": "goes19-conus-c05",
      "path": "sat/goes19/conus/c05",
      "title": "C05 · 1.6 µm (Snow/Ice)",
      "group": "channel",
      "bt": false,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/gray_refl.png",
        "ticks": [
          {
            "t": "100",
            "p": 0.0
          },
          {
            "t": "50",
            "p": 0.5
          },
          {
            "t": "0",
            "p": 1.0
          }
        ],
        "cap": "Reflectance (%)"
      }
    },
    {
      "key": "c06",
      "id": "goes19-conus-c06",
      "path": "sat/goes19/conus/c06",
      "title": "C06 · 2.2 µm (Cloud particle)",
      "group": "channel",
      "bt": false,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/gray_refl.png",
        "ticks": [
          {
            "t": "100",
            "p": 0.0
          },
          {
            "t": "50",
            "p": 0.5
          },
          {
            "t": "0",
            "p": 1.0
          }
        ],
        "cap": "Reflectance (%)"
      }
    },
    {
      "key": "c07",
      "id": "goes19-conus-c07",
      "path": "sat/goes19/conus/c07",
      "title": "C07 · 3.9 µm (Shortwave IR)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/grayscale.png",
        "ticks": [
          {
            "t": "30",
            "p": 0.0
          },
          {
            "t": "−10",
            "p": 0.3333
          },
          {
            "t": "−50",
            "p": 0.6667
          },
          {
            "t": "−90",
            "p": 1.0
          }
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c08",
      "id": "goes19-conus-c08",
      "path": "sat/goes19/conus/c08",
      "title": "C08 · 6.2 µm (Upper-level WV)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/wv_tat.png",
        "ticks": [
          {
            "t": "0",
            "p": 0.0
          },
          {
            "t": "−30",
            "p": 0.3333
          },
          {
            "t": "−60",
            "p": 0.6667
          },
          {
            "t": "−90",
            "p": 1.0
          }
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c09",
      "id": "goes19-conus-c09",
      "path": "sat/goes19/conus/c09",
      "title": "C09 · 6.9 µm (Mid-level WV)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/wv_tat.png",
        "ticks": [
          {
            "t": "0",
            "p": 0.0
          },
          {
            "t": "−30",
            "p": 0.3333
          },
          {
            "t": "−60",
            "p": 0.6667
          },
          {
            "t": "−90",
            "p": 1.0
          }
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c10",
      "id": "goes19-conus-c10",
      "path": "sat/goes19/conus/c10",
      "title": "C10 · 7.3 µm (Low-level WV)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/wv_tat.png",
        "ticks": [
          {
            "t": "0",
            "p": 0.0
          },
          {
            "t": "−30",
            "p": 0.3333
          },
          {
            "t": "−60",
            "p": 0.6667
          },
          {
            "t": "−90",
            "p": 1.0
          }
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c11",
      "id": "goes19-conus-c11",
      "path": "sat/goes19/conus/c11",
      "title": "C11 · 8.4 µm (Cloud-top phase)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          {
            "t": "40",
            "p": 0.0
          },
          {
            "t": "0",
            "p": 0.2963
          },
          {
            "t": "−40",
            "p": 0.5926
          },
          {
            "t": "−80",
            "p": 0.8889
          }
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c12",
      "id": "goes19-conus-c12",
      "path": "sat/goes19/conus/c12",
      "title": "C12 · 9.6 µm (Ozone)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          {
            "t": "40",
            "p": 0.0
          },
          {
            "t": "0",
            "p": 0.2963
          },
          {
            "t": "−40",
            "p": 0.5926
          },
          {
            "t": "−80",
            "p": 0.8889
          }
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "irbd",
      "id": "goes19-conus-irbd",
      "path": "sat/goes19/conus/irbd",
      "title": "C13 · 10.3 µm (IR, Dvorak BD)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/dvorak.png",
        "ticks": [
          {
            "t": "40",
            "p": 0.0
          },
          {
            "t": "0",
            "p": 0.2963
          },
          {
            "t": "−40",
            "p": 0.5926
          },
          {
            "t": "−80",
            "p": 0.8889
          }
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c14",
      "id": "goes19-conus-c14",
      "path": "sat/goes19/conus/c14",
      "title": "C14 · 11.2 µm (IR window)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          {
            "t": "40",
            "p": 0.0
          },
          {
            "t": "0",
            "p": 0.2963
          },
          {
            "t": "−40",
            "p": 0.5926
          },
          {
            "t": "−80",
            "p": 0.8889
          }
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c15",
      "id": "goes19-conus-c15",
      "path": "sat/goes19/conus/c15",
      "title": "C15 · 12.3 µm (Dirty IR)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          {
            "t": "40",
            "p": 0.0
          },
          {
            "t": "0",
            "p": 0.2963
          },
          {
            "t": "−40",
            "p": 0.5926
          },
          {
            "t": "−80",
            "p": 0.8889
          }
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c16",
      "id": "goes19-conus-c16",
      "path": "sat/goes19/conus/c16",
      "title": "C16 · 13.3 µm (CO₂)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          {
            "t": "40",
            "p": 0.0
          },
          {
            "t": "0",
            "p": 0.2963
          },
          {
            "t": "−40",
            "p": 0.5926
          },
          {
            "t": "−80",
            "p": 0.8889
          }
        ],
        "cap": "Brightness temperature (°C)"
      }
    }
  ],
  "himawari9": {
    "sector": "wpac",
    "products": [
      {
        "key": "ir",
        "id": "himawari9-wpac-ir",
        "path": "sat/himawari9/wpac/ir",
        "title": "B13 · 10.4 µm (Clean IR)",
        "group": "channel",
        "bt": true,
        "dayOnly": false,
        "cbar": {
          "img": "cbars/rainbow_ir.png",
          "ticks": [
            {
              "t": "40",
              "p": 0.0
            },
            {
              "t": "0",
              "p": 0.2963
            },
            {
              "t": "−40",
              "p": 0.5926
            },
            {
              "t": "−80",
              "p": 0.8889
            }
          ],
          "cap": "Brightness temperature (°C)"
        }
      },
      {
        "key": "sandwich",
        "id": "himawari9-wpac-sandwich",
        "path": "sat/himawari9/wpac/sandwich",
        "title": "Sandwich (VIS × IR)",
        "group": "composite",
        "bt": true,
        "dayOnly": true,
        "cbar": {
          "img": "cbars/rainbow_ir.png",
          "ticks": [
            {
              "t": "40",
              "p": 0.0
            },
            {
              "t": "0",
              "p": 0.2963
            },
            {
              "t": "−40",
              "p": 0.5926
            },
            {
              "t": "−80",
              "p": 0.8889
            }
          ],
          "cap": "Brightness temperature (°C)"
        }
      },
      {
        "key": "truecolor",
        "id": "himawari9-wpac-truecolor",
        "path": "sat/himawari9/wpac/truecolor",
        "title": "True Color (GeoColor-lite)",
        "group": "composite",
        "bt": false,
        "dayOnly": false,
        "cbar": null
      },
      {
        "key": "airmass",
        "id": "himawari9-wpac-airmass",
        "path": "sat/himawari9/wpac/airmass",
        "title": "Air Mass RGB",
        "group": "rgb",
        "bt": true,
        "dayOnly": false,
        "cbar": null
      },
      {
        "key": "ash",
        "id": "himawari9-wpac-ash",
        "path": "sat/himawari9/wpac/ash",
        "title": "Ash RGB",
        "group": "rgb",
        "bt": true,
        "dayOnly": false,
        "cbar": null
      },
      {
        "key": "daycloudphase",
        "id": "himawari9-wpac-daycloudphase",
        "path": "sat/himawari9/wpac/daycloudphase",
        "title": "Day Cloud Phase Distinction",
        "group": "rgb",
        "bt": true,
        "dayOnly": true,
        "cbar": null
      },
      {
        "key": "dayconvection",
        "id": "himawari9-wpac-dayconvection",
        "path": "sat/himawari9/wpac/dayconvection",
        "title": "Day Convection RGB",
        "group": "rgb",
        "bt": false,
        "dayOnly": true,
        "cbar": null
      },
      {
        "key": "daylandcloud",
        "id": "himawari9-wpac-daylandcloud",
        "path": "sat/himawari9/wpac/daylandcloud",
        "title": "Day Land Cloud (Natural Color)",
        "group": "rgb",
        "bt": false,
        "dayOnly": true,
        "cbar": null
      },
      {
        "key": "snowfog",
        "id": "himawari9-wpac-snowfog",
        "path": "sat/himawari9/wpac/snowfog",
        "title": "Day Snow-Fog RGB",
        "group": "rgb",
        "bt": false,
        "dayOnly": true,
        "cbar": null
      },
      {
        "key": "dust",
        "id": "himawari9-wpac-dust",
        "path": "sat/himawari9/wpac/dust",
        "title": "Dust RGB",
        "group": "rgb",
        "bt": true,
        "dayOnly": false,
        "cbar": null
      },
      {
        "key": "firetemp",
        "id": "himawari9-wpac-firetemp",
        "path": "sat/himawari9/wpac/firetemp",
        "title": "Fire Temperature RGB",
        "group": "rgb",
        "bt": false,
        "dayOnly": true,
        "cbar": null
      },
      {
        "key": "nightmicro",
        "id": "himawari9-wpac-nightmicro",
        "path": "sat/himawari9/wpac/nightmicro",
        "title": "Nighttime Microphysics",
        "group": "rgb",
        "bt": true,
        "dayOnly": false,
        "cbar": null
      },
      {
        "key": "b01",
        "id": "himawari9-wpac-b01",
        "path": "sat/himawari9/wpac/b01",
        "title": "B01 · 0.47 µm (Blue)",
        "group": "channel",
        "bt": false,
        "dayOnly": true,
        "cbar": {
          "img": "cbars/gray_refl.png",
          "ticks": [
            {
              "t": "100",
              "p": 0.0
            },
            {
              "t": "50",
              "p": 0.5
            },
            {
              "t": "0",
              "p": 1.0
            }
          ],
          "cap": "Reflectance (%)"
        }
      },
      {
        "key": "b02",
        "id": "himawari9-wpac-b02",
        "path": "sat/himawari9/wpac/b02",
        "title": "B02 · 0.51 µm (Green)",
        "group": "channel",
        "bt": false,
        "dayOnly": true,
        "cbar": {
          "img": "cbars/gray_refl.png",
          "ticks": [
            {
              "t": "100",
              "p": 0.0
            },
            {
              "t": "50",
              "p": 0.5
            },
            {
              "t": "0",
              "p": 1.0
            }
          ],
          "cap": "Reflectance (%)"
        }
      },
      {
        "key": "b03",
        "id": "himawari9-wpac-b03",
        "path": "sat/himawari9/wpac/b03",
        "title": "B03 · 0.64 µm (Red visible)",
        "group": "channel",
        "bt": false,
        "dayOnly": true,
        "cbar": {
          "img": "cbars/gray_refl.png",
          "ticks": [
            {
              "t": "100",
              "p": 0.0
            },
            {
              "t": "50",
              "p": 0.5
            },
            {
              "t": "0",
              "p": 1.0
            }
          ],
          "cap": "Reflectance (%)"
        }
      },
      {
        "key": "b04",
        "id": "himawari9-wpac-b04",
        "path": "sat/himawari9/wpac/b04",
        "title": "B04 · 0.86 µm (Veggie NIR)",
        "group": "channel",
        "bt": false,
        "dayOnly": true,
        "cbar": {
          "img": "cbars/gray_refl.png",
          "ticks": [
            {
              "t": "100",
              "p": 0.0
            },
            {
              "t": "50",
              "p": 0.5
            },
            {
              "t": "0",
              "p": 1.0
            }
          ],
          "cap": "Reflectance (%)"
        }
      },
      {
        "key": "b05",
        "id": "himawari9-wpac-b05",
        "path": "sat/himawari9/wpac/b05",
        "title": "B05 · 1.6 µm (Snow/Ice)",
        "group": "channel",
        "bt": false,
        "dayOnly": true,
        "cbar": {
          "img": "cbars/gray_refl.png",
          "ticks": [
            {
              "t": "100",
              "p": 0.0
            },
            {
              "t": "50",
              "p": 0.5
            },
            {
              "t": "0",
              "p": 1.0
            }
          ],
          "cap": "Reflectance (%)"
        }
      },
      {
        "key": "b06",
        "id": "himawari9-wpac-b06",
        "path": "sat/himawari9/wpac/b06",
        "title": "B06 · 2.3 µm (Cloud particle)",
        "group": "channel",
        "bt": false,
        "dayOnly": true,
        "cbar": {
          "img": "cbars/gray_refl.png",
          "ticks": [
            {
              "t": "100",
              "p": 0.0
            },
            {
              "t": "50",
              "p": 0.5
            },
            {
              "t": "0",
              "p": 1.0
            }
          ],
          "cap": "Reflectance (%)"
        }
      },
      {
        "key": "b07",
        "id": "himawari9-wpac-b07",
        "path": "sat/himawari9/wpac/b07",
        "title": "B07 · 3.9 µm (Shortwave IR)",
        "group": "channel",
        "bt": true,
        "dayOnly": false,
        "cbar": {
          "img": "cbars/grayscale.png",
          "ticks": [
            {
              "t": "30",
              "p": 0.0
            },
            {
              "t": "−10",
              "p": 0.3333
            },
            {
              "t": "−50",
              "p": 0.6667
            },
            {
              "t": "−90",
              "p": 1.0
            }
          ],
          "cap": "Brightness temperature (°C)"
        }
      },
      {
        "key": "b08",
        "id": "himawari9-wpac-b08",
        "path": "sat/himawari9/wpac/b08",
        "title": "B08 · 6.2 µm (Upper-level WV)",
        "group": "channel",
        "bt": true,
        "dayOnly": false,
        "cbar": {
          "img": "cbars/wv_tat.png",
          "ticks": [
            {
              "t": "0",
              "p": 0.0
            },
            {
              "t": "−30",
              "p": 0.3333
            },
            {
              "t": "−60",
              "p": 0.6667
            },
            {
              "t": "−90",
              "p": 1.0
            }
          ],
          "cap": "Brightness temperature (°C)"
        }
      },
      {
        "key": "b09",
        "id": "himawari9-wpac-b09",
        "path": "sat/himawari9/wpac/b09",
        "title": "B09 · 6.9 µm (Mid-level WV)",
        "group": "channel",
        "bt": true,
        "dayOnly": false,
        "cbar": {
          "img": "cbars/wv_tat.png",
          "ticks": [
            {
              "t": "0",
              "p": 0.0
            },
            {
              "t": "−30",
              "p": 0.3333
            },
            {
              "t": "−60",
              "p": 0.6667
            },
            {
              "t": "−90",
              "p": 1.0
            }
          ],
          "cap": "Brightness temperature (°C)"
        }
      },
      {
        "key": "b10",
        "id": "himawari9-wpac-b10",
        "path": "sat/himawari9/wpac/b10",
        "title": "B10 · 7.3 µm (Low-level WV)",
        "group": "channel",
        "bt": true,
        "dayOnly": false,
        "cbar": {
          "img": "cbars/wv_tat.png",
          "ticks": [
            {
              "t": "0",
              "p": 0.0
            },
            {
              "t": "−30",
              "p": 0.3333
            },
            {
              "t": "−60",
              "p": 0.6667
            },
            {
              "t": "−90",
              "p": 1.0
            }
          ],
          "cap": "Brightness temperature (°C)"
        }
      },
      {
        "key": "b11",
        "id": "himawari9-wpac-b11",
        "path": "sat/himawari9/wpac/b11",
        "title": "B11 · 8.6 µm (Cloud-top phase)",
        "group": "channel",
        "bt": true,
        "dayOnly": false,
        "cbar": {
          "img": "cbars/rainbow_ir.png",
          "ticks": [
            {
              "t": "40",
              "p": 0.0
            },
            {
              "t": "0",
              "p": 0.2963
            },
            {
              "t": "−40",
              "p": 0.5926
            },
            {
              "t": "−80",
              "p": 0.8889
            }
          ],
          "cap": "Brightness temperature (°C)"
        }
      },
      {
        "key": "b12",
        "id": "himawari9-wpac-b12",
        "path": "sat/himawari9/wpac/b12",
        "title": "B12 · 9.6 µm (Ozone)",
        "group": "channel",
        "bt": true,
        "dayOnly": false,
        "cbar": {
          "img": "cbars/rainbow_ir.png",
          "ticks": [
            {
              "t": "40",
              "p": 0.0
            },
            {
              "t": "0",
              "p": 0.2963
            },
            {
              "t": "−40",
              "p": 0.5926
            },
            {
              "t": "−80",
              "p": 0.8889
            }
          ],
          "cap": "Brightness temperature (°C)"
        }
      },
      {
        "key": "irbd",
        "id": "himawari9-wpac-irbd",
        "path": "sat/himawari9/wpac/irbd",
        "title": "B13 · 10.4 µm (IR, Dvorak BD)",
        "group": "channel",
        "bt": true,
        "dayOnly": false,
        "cbar": {
          "img": "cbars/dvorak.png",
          "ticks": [
            {
              "t": "40",
              "p": 0.0
            },
            {
              "t": "0",
              "p": 0.2963
            },
            {
              "t": "−40",
              "p": 0.5926
            },
            {
              "t": "−80",
              "p": 0.8889
            }
          ],
          "cap": "Brightness temperature (°C)"
        }
      },
      {
        "key": "b14",
        "id": "himawari9-wpac-b14",
        "path": "sat/himawari9/wpac/b14",
        "title": "B14 · 11.2 µm (IR window)",
        "group": "channel",
        "bt": true,
        "dayOnly": false,
        "cbar": {
          "img": "cbars/rainbow_ir.png",
          "ticks": [
            {
              "t": "40",
              "p": 0.0
            },
            {
              "t": "0",
              "p": 0.2963
            },
            {
              "t": "−40",
              "p": 0.5926
            },
            {
              "t": "−80",
              "p": 0.8889
            }
          ],
          "cap": "Brightness temperature (°C)"
        }
      },
      {
        "key": "b15",
        "id": "himawari9-wpac-b15",
        "path": "sat/himawari9/wpac/b15",
        "title": "B15 · 12.4 µm (Dirty IR)",
        "group": "channel",
        "bt": true,
        "dayOnly": false,
        "cbar": {
          "img": "cbars/rainbow_ir.png",
          "ticks": [
            {
              "t": "40",
              "p": 0.0
            },
            {
              "t": "0",
              "p": 0.2963
            },
            {
              "t": "−40",
              "p": 0.5926
            },
            {
              "t": "−80",
              "p": 0.8889
            }
          ],
          "cap": "Brightness temperature (°C)"
        }
      },
      {
        "key": "b16",
        "id": "himawari9-wpac-b16",
        "path": "sat/himawari9/wpac/b16",
        "title": "B16 · 13.3 µm (CO₂)",
        "group": "channel",
        "bt": true,
        "dayOnly": false,
        "cbar": {
          "img": "cbars/rainbow_ir.png",
          "ticks": [
            {
              "t": "40",
              "p": 0.0
            },
            {
              "t": "0",
              "p": 0.2963
            },
            {
              "t": "−40",
              "p": 0.5926
            },
            {
              "t": "−80",
              "p": 0.8889
            }
          ],
          "cap": "Brightness temperature (°C)"
        }
      }
    ]
  }
};
