/* GENERATED by tat-satellite-render s2_products_export.py -- do not
 * hand-edit. Regenerate after registry/recipe changes:
 *   python s2_products_export.py --out <TAT>/satellite/explorer
 * Presentation mirror of the registry suite (SSOT: s2_recipes +
 * s2_registry); products.json on R2 carries the same rows. */
window.TVProducts = {
  "base": "https://cdn.triple-a-tropics.com/shadow/",
  "sector": "conus",
  "products": [
    {
      "key": "ir",
      "id": "goes19-conus-ir",
      "path": "sat/goes19/conus/ir",
      "title": "C13 · 10.3 µm (Clean IR)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          "40",
          "0",
          "−40",
          "−80"
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "sandwich",
      "id": "goes19-conus-sandwich",
      "path": "sat/goes19/conus/sandwich",
      "title": "Sandwich (VIS × IR)",
      "group": "composite",
      "bt": true,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          "40",
          "0",
          "−40",
          "−80"
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "truecolor",
      "id": "goes19-conus-truecolor",
      "path": "sat/goes19/conus/truecolor",
      "title": "True Color (GeoColor-lite)",
      "group": "composite",
      "bt": false,
      "dayOnly": false,
      "cbar": null
    },
    {
      "key": "airmass",
      "id": "goes19-conus-airmass",
      "path": "sat/goes19/conus/airmass",
      "title": "Air Mass RGB",
      "group": "rgb",
      "bt": false,
      "dayOnly": false,
      "cbar": null
    },
    {
      "key": "daycloudphase",
      "id": "goes19-conus-daycloudphase",
      "path": "sat/goes19/conus/daycloudphase",
      "title": "Day Cloud Phase Distinction",
      "group": "rgb",
      "bt": false,
      "dayOnly": true,
      "cbar": null
    },
    {
      "key": "dust",
      "id": "goes19-conus-dust",
      "path": "sat/goes19/conus/dust",
      "title": "Dust RGB",
      "group": "rgb",
      "bt": false,
      "dayOnly": false,
      "cbar": null
    },
    {
      "key": "firetemp",
      "id": "goes19-conus-firetemp",
      "path": "sat/goes19/conus/firetemp",
      "title": "Fire Temperature RGB",
      "group": "rgb",
      "bt": false,
      "dayOnly": true,
      "cbar": null
    },
    {
      "key": "nightmicro",
      "id": "goes19-conus-nightmicro",
      "path": "sat/goes19/conus/nightmicro",
      "title": "Nighttime Microphysics",
      "group": "rgb",
      "bt": false,
      "dayOnly": false,
      "cbar": null
    },
    {
      "key": "c01",
      "id": "goes19-conus-c01",
      "path": "sat/goes19/conus/c01",
      "title": "C01 · 0.47 µm (Blue)",
      "group": "channel",
      "bt": false,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/gray_refl.png",
        "ticks": [
          "100",
          "50",
          "0"
        ],
        "cap": "Reflectance (%)"
      }
    },
    {
      "key": "c02",
      "id": "goes19-conus-c02",
      "path": "sat/goes19/conus/c02",
      "title": "C02 · 0.64 µm (Red visible)",
      "group": "channel",
      "bt": false,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/gray_refl.png",
        "ticks": [
          "100",
          "50",
          "0"
        ],
        "cap": "Reflectance (%)"
      }
    },
    {
      "key": "c03",
      "id": "goes19-conus-c03",
      "path": "sat/goes19/conus/c03",
      "title": "C03 · 0.86 µm (Veggie NIR)",
      "group": "channel",
      "bt": false,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/gray_refl.png",
        "ticks": [
          "100",
          "50",
          "0"
        ],
        "cap": "Reflectance (%)"
      }
    },
    {
      "key": "c04",
      "id": "goes19-conus-c04",
      "path": "sat/goes19/conus/c04",
      "title": "C04 · 1.37 µm (Cirrus)",
      "group": "channel",
      "bt": false,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/gray_refl.png",
        "ticks": [
          "100",
          "50",
          "0"
        ],
        "cap": "Reflectance (%)"
      }
    },
    {
      "key": "c05",
      "id": "goes19-conus-c05",
      "path": "sat/goes19/conus/c05",
      "title": "C05 · 1.6 µm (Snow/Ice)",
      "group": "channel",
      "bt": false,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/gray_refl.png",
        "ticks": [
          "100",
          "50",
          "0"
        ],
        "cap": "Reflectance (%)"
      }
    },
    {
      "key": "c06",
      "id": "goes19-conus-c06",
      "path": "sat/goes19/conus/c06",
      "title": "C06 · 2.2 µm (Cloud particle)",
      "group": "channel",
      "bt": false,
      "dayOnly": true,
      "cbar": {
        "img": "cbars/gray_refl.png",
        "ticks": [
          "100",
          "50",
          "0"
        ],
        "cap": "Reflectance (%)"
      }
    },
    {
      "key": "c07",
      "id": "goes19-conus-c07",
      "path": "sat/goes19/conus/c07",
      "title": "C07 · 3.9 µm (Shortwave IR)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/grayscale.png",
        "ticks": [
          "30",
          "−10",
          "−50",
          "−90"
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c08",
      "id": "goes19-conus-c08",
      "path": "sat/goes19/conus/c08",
      "title": "C08 · 6.2 µm (Upper-level WV)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/wv_tat.png",
        "ticks": [
          "0",
          "−30",
          "−60",
          "−90"
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c09",
      "id": "goes19-conus-c09",
      "path": "sat/goes19/conus/c09",
      "title": "C09 · 6.9 µm (Mid-level WV)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/wv_tat.png",
        "ticks": [
          "0",
          "−30",
          "−60",
          "−90"
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c10",
      "id": "goes19-conus-c10",
      "path": "sat/goes19/conus/c10",
      "title": "C10 · 7.3 µm (Low-level WV)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/wv_tat.png",
        "ticks": [
          "0",
          "−30",
          "−60",
          "−90"
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c11",
      "id": "goes19-conus-c11",
      "path": "sat/goes19/conus/c11",
      "title": "C11 · 8.4 µm (Cloud-top phase)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          "40",
          "0",
          "−40",
          "−80"
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c12",
      "id": "goes19-conus-c12",
      "path": "sat/goes19/conus/c12",
      "title": "C12 · 9.6 µm (Ozone)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          "40",
          "0",
          "−40",
          "−80"
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "irbd",
      "id": "goes19-conus-irbd",
      "path": "sat/goes19/conus/irbd",
      "title": "C13 · 10.3 µm (IR, Dvorak BD)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/dvorak.png",
        "ticks": [
          "40",
          "0",
          "−40",
          "−80"
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c14",
      "id": "goes19-conus-c14",
      "path": "sat/goes19/conus/c14",
      "title": "C14 · 11.2 µm (IR window)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          "40",
          "0",
          "−40",
          "−80"
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c15",
      "id": "goes19-conus-c15",
      "path": "sat/goes19/conus/c15",
      "title": "C15 · 12.3 µm (Dirty IR)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          "40",
          "0",
          "−40",
          "−80"
        ],
        "cap": "Brightness temperature (°C)"
      }
    },
    {
      "key": "c16",
      "id": "goes19-conus-c16",
      "path": "sat/goes19/conus/c16",
      "title": "C16 · 13.3 µm (CO₂)",
      "group": "channel",
      "bt": true,
      "dayOnly": false,
      "cbar": {
        "img": "cbars/rainbow_ir.png",
        "ticks": [
          "40",
          "0",
          "−40",
          "−80"
        ],
        "cap": "Brightness temperature (°C)"
      }
    }
  ]
};
